---
galaxy_info:
  author: 'Tomasz Baczynski'
  description: Install and setup chrony NTP service
  company: DreamHost/BulIT

  license: BSD

  min_ansible_version: 2.7

  platforms:
    - name: Ubuntu
      versions:
        - bionic
    - name: Debian
      versions:
        - buster

  galaxy_tags:
    - system
    - ntp
    - chrony

dependencies: []

...
