apiVersion: apps/v1
kind: Deployment
metadata:
  name: netatmo-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: netatmo-exporter
  template:
    metadata:
      name: netatmo-exporter
      labels:
        app: netatmo-exporter
    spec:
      containers:
      - name: netatmo-exporter
        image: ghcr.io/xperimental/netatmo-exporter:1.4.0
        envFrom:
          - secretRef:
              name: netatmo-exporter
