apiVersion: apps/v1
kind: Deployment
metadata:
  name: netatmo-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: netatmo-exporter
  template:
    metadata:
      name: netatmo-exporter
      labels:
        app: netatmo-exporter
    spec:
      containers:
      - name: netatmo-exporter
        image: ghcr.io/xperimental/netatmo-exporter:2.0.1
        env:
          - name: NETATMO_EXPORTER_TOKEN_FILE
            value: /data/token.json
        envFrom:
          - secretRef:
              name: netatmo-exporter
        volumeMounts:
        - name: data-volume
          mountPath: /data
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: netatmo-exporter-data
