apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: netatmo-exporter
spec:
  secretStoreRef:
    name: production
    kind: ClusterSecretStore
  refreshInterval: "1h"
  dataFrom:
  - extract:
      key: netatmo-exporter
