---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default

resources:
 - deploy.yaml
 - service.yaml

commonLabels:
  app: netatmo-exporter

secretGenerator:
  - name: netatmo-exporter
    env: secret.txt
    type: Opaque
