apiVersion: v1
kind: Service
metadata:
  labels:
    name: netatmo-exporter
  name: netatmo-exporter
  namespace: kube-system
spec:
  selector:
    app: netatmo-exporter
  ports:
  - name: netatmo-exporter
    protocol: TCP
    port: 9210
