apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: loki
spec:
  secretStoreRef:
    name: production
    kind: ClusterSecretStore
  refreshInterval: "1h"
  target:
    template:
      data:
        loki.yaml: "{{ .loki_config }}"
  dataFrom:
  - extract:
      key: loki
