---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
 - helm/loki/templates/statefulset.yaml
 - helm/loki/templates/serviceaccount.yaml
 - helm/loki/templates/service.yaml
 - helm/loki/templates/service-memberlist.yaml

commonLabels:
  app: loki

secretGenerator:
  - name: loki
    files:
      - loki.yaml=helm/loki.dist.yaml
    type: Opaque
