---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: tautulli
  labels:
    k8s-app: tautulli
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        k8s-app: tautulli
    spec:
      containers:
      - name: tautulli
        image: tautulli/tautulli
        imagePullPolicy: Always
        ports:
        - containerPort: 8181
        env:
          - name: TZ
            value: "EST5EDT"
        livenessProbe:
          failureThreshold: 10000
          httpGet:
            path: /
            port: 8181
        volumeMounts:
          - mountPath: "/config"
            name: config
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: tautulli-config
