---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: tautulli
  labels:
    k8s-app: tautulli
    stable.k8s.psg.io/kcm.class: "default"
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
    - hosts:
      - "tautulli.k.oneill.net"
      secretName: "tautulli-tls"
  rules:
    - host: "tautulli.k.oneill.net"
      http:
        paths:
          - path: /
            backend:
              serviceName: tautulli
              servicePort: 8181
