---
apiVersion: v1
kind: Service
metadata:
  name: tautulli
  labels:
    k8s-app: tautulli
spec:
  ports:
  - port: 8181
    targetPort: 8181
    protocol: TCP
    name: http
  selector:
    k8s-app: tautulli
