---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default

resources:
- deployment.yaml
- pvc.yaml
- service.yaml
- ingress.yaml

images:
- name: linuxserver/qbittorrent
  newTag: 5.1.2

labels:
- pairs:
    app.kubernetes.io/name: qbittorrent
    app.kubernetes.io/instance: qbittorrent
  includeSelectors: true
