---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: qbittorrent-config
  labels:
    k8s-app: qbittorrent
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
