---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
namePrefix: blackbox-

resources:
 - deploy.yaml
 - service.yaml

commonLabels:
  app: blackbox-exporter

configMapGenerator:
  - name: config
    files:
      - config.yaml

