download_url: https://galaxy.ansible.com/api/v3/plugin/ansible/content/published/collections/artifacts/artis3n-tailscale-1.0.1.tar.gz
format_version: 1.0.0
name: tailscale
namespace: artis3n
server: https://galaxy.ansible.com/api/
signatures: []
version: 1.0.1
version_url: /api/v3/plugin/ansible/content/published/collections/index/artis3n/tailscale/versions/1.0.1/
