---
# Source: promtail/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: promtail
  namespace: default
  labels:
    helm.sh/chart: promtail-4.2.1
    app.kubernetes.io/name: promtail
    app.kubernetes.io/instance: promtail
    app.kubernetes.io/version: "2.5.0"
    app.kubernetes.io/managed-by: Helm
