---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: alertmanager-data
  namespace: kube-system
  labels:
    k8s-app: alertmanager
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
