---
- name: "Load variables"
  hosts: localhost
  connection: local
  gather_facts: no
  tags: [ always ]
  tasks:
    - include_vars: vars/vault.yaml

- hosts: localhost
  connection: local
  gather_facts: no
  become: no
  tasks:
    - name: "Destroy falcon.fnord.net"
      digital_ocean: 
        state: deleted
        name: falcon
        unique_name: yes
        api_token: "{{ do_api_token }}"
    - name: "Delete DNS entry for falcon.fnord.net"
      dnsmadeeasy:
        domain: fnord.net
        record_name: falcon
        record_type: A
        state: absent
        account_key: "{{ dme_api_key }}"
        account_secret: "{{ dme_secret_key }}"
