---
- src: resmo.ntp
  version: '0.4.0'
- src: geerlingguy.docker
  version: '2.5.4'
- src: ANXS.generic-users
  version: v1.1.0
- src: Yannik.relaymail
  version: v1.2.1
- name: SphericalElephant.borgbackup
  src: https://github.com/claytono/ansible-role-borgbackup
- src: https://github.com/UnderGreen/ansible-prometheus-node-exporter
  name: UnderGreen.prometheus-node-exporter
  version: 'v1.4.0'
