---
- src: resmo.ntp
  version: '0.4.0'
- src: https://github.com/mongrelion/ansible-role-docker
  version: '0.2.1'
  name: mongrelion.docker
- src: ANXS.generic-users
  version: v1.1.0
- src: Yannik.relaymail
  version: v1.2.1
- name: SphericalElephant.borgbackup
  src: https://github.com/claytono/ansible-role-borgbackup
- src: https://github.com/UnderGreen/ansible-prometheus-node-exporter
  name: UnderGreen.prometheus-node-exporter
  version: ea5aba07fdb59de5e2e3faaaae587ace193d9669
