---
- src: resmo.ntp
  version: '0.4.0'
- src: geerlingguy.docker
  version: '2.5.4'
- src: ANXS.generic-users
  version: v1.1.0
- name: Yannik.relaymail
  src: https://github.com/Yannik/ansible-role-relaymail.git
  version: d0d7201b1b4a84ad358a4bccbbfa2232f80e6eac
- name: SphericalElephant.borgbackup
  src: https://github.com/claytono/ansible-role-borgbackup
- src: https://github.com/UnderGreen/ansible-prometheus-node-exporter
  name: UnderGreen.prometheus-node-exporter
  version: 'v1.4.0'
