---
- src: tbaczynski.chrony
  version: 'v1.0.4'
- src: geerlingguy.docker
  version: '3.1.2'
- src: geerlingguy.containerd
  version: '1.3.1'
- src: mprahl.lets-encrypt-route-53
  version: 'v5.1.2'
- src: ANXS.generic-users
  version: v1.1.0
- name: Yannik.relaymail
  src: https://github.com/Yannik/ansible-role-relaymail.git
  version: d0d7201b1b4a84ad358a4bccbbfa2232f80e6eac
- name: artis3n.tailscale
  version: 'v4.4.3'
- src: https://github.com/UnderGreen/ansible-prometheus-node-exporter
  name: UnderGreen.prometheus-node-exporter
  version: 'v1.4.0'
- src: michaelrigart.interfaces
  version: 'v1.13.3'
- src: https://github.com/layereight/ansible-wifi
  name: layereight.wifi
  version: '1.3.0'
