---
- hosts: all
  gather_facts: no
  tasks:
    - include_vars: vars/vault.yaml

  roles:
    - { role: install_python, when: "setup_upgrade | default(false) | bool" }

- hosts: all
  roles:
    - { role: setup_upgrade, when: "setup_upgrade | default(false) | bool" }

- hosts: all
  roles:
    - common
    - ANXS.generic-users
    - resmo.ntp
    - role: Yannik.relaymail
      when: is_vagrant is undefined or not is_vagrant
    - role: SphericalElephant.borgbackup
      when: "borg_client_enabled | default(true)"

- hosts: docker
  roles:
    - mongrelion.docker

- hosts: plex-client
  roles:
    - role: plex-client

- hosts: plex-server
  roles:
    - role: plex-server
