---
- hosts: all
  gather_facts: no
  tasks:
    - include_vars: vars/vault.yaml

  roles:
    - { role: install_python, when: "setup_upgrade | default(false) | bool" }

- hosts: all
  roles:
    - { role: setup_upgrade, when: "setup_upgrade | default(false) | bool" }

- hosts: all
  roles:
    - common
    - ANXS.generic-users
    - resmo.ntp

- hosts: docker
  roles:
    - angstwad.docker_ubuntu

- hosts: plex-client
  roles:
    - role: plex-client
