---
- hosts: all
  gather_facts: no
  tasks:
    - include_vars: vars/vault.yaml

  roles:
    - role: install_python
      when: "setup_upgrade | default(false) | bool"
      tags: setup_upgrade

- hosts: all
  roles:
    - role: setup_upgrade
      when: "setup_upgrade | default(false) | bool"
      tags: setup_upgrade

- hosts: all
  roles:
    - common
    - ANXS.generic-users
    - resmo.ntp
    - role: Yannik.relaymail
      when: is_vagrant is undefined or not is_vagrant
    - role: SphericalElephant.borgbackup
      when: "borg_client_enabled | default(true)"

- hosts: docker
  roles:
    - role: mongrelion.docker
      tags: docker

- hosts: kubernetes
  roles:
    - role: kubeadm
      tags: kubernetes

- hosts: plex-client
  roles:
    - role: plex-client

- hosts: plex-server
  roles:
    - role: plex-server

- hosts: nut-hosts
  roles:
    - role: UnderGreen.prometheus-node-exporter
      when: "node_exporter_enabled | default(false)"
    - role: ntd.nut

