---
- hosts: all
  gather_facts: no
  tasks:
    - include_vars: vars/vault.yaml

  roles:
    - role: install_python
      when: "setup_upgrade | default(false) | bool"
      tags: setup_upgrade

- hosts: all
  roles:
    - role: setup_upgrade
      when: "setup_upgrade | default(false) | bool"
      tags: setup_upgrade

- hosts: all
  roles:
    - common

- hosts: all
  roles:
    - ANXS.generic-users
  tasks:
    - name: Get user groups
      getent:
        database: group

    - name: Add coneill to groups if they exist
      user: name="coneill" groups="{{item}}" append=yes
      when: item in ansible_facts.getent_group
      with_items:
       - libvirt

- hosts: all
  roles:
    - tbaczynski.chrony
    - role: Yannik.relaymail
      when: is_vagrant is undefined or not is_vagrant
    - role: fiaasco.borgbackup
      tags: borg
      when: "borg_client_enabled | default(true)"

- hosts: certbot
  become: yes
  roles:
    - role: certbot
      tags: certbot

- hosts: docker
  roles:
    - role: geerlingguy.docker
      tags: docker

- hosts: all
  roles:
    - role: artis3n.tailscale
      tags: tailscale

- hosts: kubernetes
  roles:
    - role: kubeadm
      tags: kubernetes

- hosts: all
  roles:
    - role: UnderGreen.prometheus-node-exporter
      tags: prom
      when: "node_exporter_enabled | default(false)"
