---
- name: "Install prereq packages"
  apt:
    name:
    - "nfs-common"

- name: "Disabling accepting ICMP redirects"
  sysctl:
    name: "net.ipv4.conf.all.accept_redirects"
    value: "0"


- name: "Disabling sending ICMP redirects"
  sysctl:
    name: "net.ipv4.conf.all.send_redirects"
    value: "0"

- name: "Turn off swap"
  shell: "swapoff -a"

- name: "Disable swap in fstab"
  replace:
    path: /etc/fstab
    regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
    replace: '# \1'

- name: "Disable nftables on Debian"
  alternatives:
    name: iptables
    path: /usr/sbin/iptables-legacy
  when: ansible_facts['distribution'] == "Debian"

- name: "Disable systemd-resolved"
  systemd:
    name: systemd-resolved
    enabled: no
    state: stopped

- name: "Disable systemd-resolved dhclient integration"
  file:
    path: /etc/dhcp/dhclient-enter-hooks.d/resolved
    state: absent
  register: dhclient_resolved_file

- name: "Install apt-transport-https"
  apt:
     name: apt-transport-https
     state: latest

- name: "Add Kubernetes APT key"
  apt_key:
    id: "2D38FEEA9169307EA071"
    url: "https://packages.cloud.google.com/apt/doc/apt-key.gpg"

- name: "Add Kubernetes APT repo"
  apt_repository:
    repo: "deb http://apt.kubernetes.io/ kubernetes-xenial main"
    filename: "kubernetes"
    update_cache: yes

- name: "Create kubeadm package pin for version"
  copy:
    dest: "/etc/apt/preferences.d/kubeadm"
    content: |
      Package: kubeadm
      Pin: version {{ kubeadm_version }}
      Pin-Priority: 900
  when: kubeadm_version is defined

- name: "Create kubelet package pin for version"
  copy:
    dest: "/etc/apt/preferences.d/kubelet"
    content: |
      Package: kubelet
      Pin: version {{ kubelet_version }}
      Pin-Priority: 900
  when: kubelet_version is defined

- name: "Create kubectl package pin for version"
  copy:
    dest: "/etc/apt/preferences.d/kubectl"
    content: |
      Package: kubectl
      Pin: version {{ kubectl_version }}
      Pin-Priority: 900
  when: kubectl_version is defined

- name: "Create kubernetes-cni package pin for version"
  copy:
    dest: "/etc/apt/preferences.d/kubernetes-cni"
    content: |
      Package: kubernetes-cni
      Pin: version {{ kubernetes_cni_version }}
      Pin-Priority: 900
  when: kubernetes_cni_version is defined

- name: "Create docker-ce package pin for version"
  copy:
    dest: "/etc/apt/preferences.d/docker"
    content: |
      Package: docker-ce
      Pin: version {{ docker_version }}*
      Pin-Priority: 900
  when: docker_version is defined

- name: "Install packages"
  apt:
    name:
    - "kubelet={{ kubelet_version }}"
    - "kubeadm={{ kubeadm_version }}"
    - "kubectl={{ kubectl_version }}"
    - "kubernetes-cni={{ kubernetes_cni_version }}"
    state: present
    allow_downgrade: yes
