---
- name: "Install prereq packages"
  apt:
    name: "{{ item }}"
  with_items:
    - "nfs-common"

- name: "Disabling accepting ICMP redirects"
  sysctl:
    name: "net.ipv4.conf.all.accept_redirects"
    value: "0"


- name: "Disabling sending ICMP redirects"
  sysctl:
    name: "net.ipv4.conf.all.send_redirects"
    value: "0"


- name: "Install apt-transport-https"
  apt:
     name: apt-transport-https
     state: latest

- name: "Add Kubernetes APT key"
  apt_key:
    url: "https://packages.cloud.google.com/apt/doc/apt-key.gpg"

- name: "Add Kubernetes APT repo"
  apt_repository:
    repo: "deb http://apt.kubernetes.io/ kubernetes-{{ ansible_distribution_release }} main"
    filename: "kubernetes"
    update_cache: yes

- name: "Create kubeadm package pin for version"
  copy:
    dest: "/etc/apt/preferences.d/kubeadm"
    content: |
      Package: kubeadm
      Pin: version {{ kubeadm_version }}
      Pin-Priority: 900
  when: kubeadm_version is defined

- name: "Create docker-engine package pin for version"
  copy:
    dest: "/etc/apt/preferences.d/docker"
    content: |
      Package: docker-engine
      Pin: version {{ docker_version }}*
      Pin-Priority: 900
  when: docker_version is defined

- name: "Install packages"
  apt:
    name: "{{ item }}"
  with_items:
    - "kubelet"
    - "kubeadm"
    - "kubectl"
    - "kubernetes-cni"

