- name: "Reset kubeadm if requested"
  command: "kubeadm reset"
  when: "kubeadm_reset |default(false) |bool"

- name: "Run kubeadm join to master"
  command: "kubeadm join --token {{ kubeadm_bootstrap_token }} {{ kubernetes_master }}:6443"
  args:
    creates: "/etc/kubernetes/kubelet.conf"
