---
# Source: node-feature-discovery/templates/nfd-worker-conf.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: release-name-node-feature-discovery-worker-conf
  namespace: node-feature-discovery
  labels:
    helm.sh/chart: node-feature-discovery-0.14.3
    app.kubernetes.io/name: node-feature-discovery
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "v0.14.3"
    app.kubernetes.io/managed-by: Helm
data:
  nfd-worker.conf: |-
    null
