---
# Source: node-feature-discovery/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: release-name-node-feature-discovery
  namespace: node-feature-discovery
  labels:
    helm.sh/chart: node-feature-discovery-0.14.3
    app.kubernetes.io/name: node-feature-discovery
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "v0.14.3"
    app.kubernetes.io/managed-by: Helm
---
# Source: node-feature-discovery/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: release-name-node-feature-discovery-gc
  namespace: node-feature-discovery
  labels:
    helm.sh/chart: node-feature-discovery-0.14.3
    app.kubernetes.io/name: node-feature-discovery
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "v0.14.3"
    app.kubernetes.io/managed-by: Helm
---
# Source: node-feature-discovery/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: release-name-node-feature-discovery-worker
  namespace: node-feature-discovery
  labels:
    helm.sh/chart: node-feature-discovery-0.14.3
    app.kubernetes.io/name: node-feature-discovery
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "v0.14.3"
    app.kubernetes.io/managed-by: Helm
