---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hass
  labels:
    k8s-app: hass
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt"
spec:
  tls:
    - hosts:
      - "hass.k.oneill.net"
      secretName: "hass-tls"
  rules:
    - host: "hass.k.oneill.net"
      http:
        paths:
          - path: /
            backend:
              serviceName: hass
              servicePort: 8123
