apiVersion: v1
kind: Service
metadata:
#  annotations:
#    prometheus.io/scrape: 'true'
  labels:
    name: hass
  name: hass
spec:
  selector:
    app: hass
  ports:
  - name: hass
    protocol: TCP
    port: 8123
