---
version: "3.8"
services:
  peanut:
    image: brandawg93/peanut:latest@sha256:f83ff012c739f9e23b1cb601b06b2352125d01965f9b65901c5062be1108e80d
    restart: unless-stopped
    volumes:
      - /etc/nut/peanut-settings.yml:/config/settings.yml:ro

  caddy:
    build: .
    restart: unless-stopped
    ports:
      - "443:443"
    environment:
      AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}"
      AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"
      AWS_REGION: "${AWS_REGION}"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - /etc/ssl/caddy:/etc/ssl/caddy
    depends_on:
      - peanut
