---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: meshcentral
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt"
spec:
  tls:
    - hosts:
      - "meshcentral.k.oneill.net"
      secretName: "meshcentral-tls"
  rules:
    - host: "meshcentral.k.oneill.net"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: meshcentral
                port:
                  number: 80
