---
# Vultr VPS running Debian 11 (bullseye)
# vc2-1c-1gb instance
tailscale_args: --advertise-exit-node # --accept-dns=false
ip_forwarding_enabled: true
restic_prometheus_config: {}
restic_host_config:
  default:
    # Use a dedicated repo.  This host has limited disk and memory, so pulling
    # the index for all other machines is not practical.
    repository: sftp:restic@luser.fnord.net:/repos/{{ ansible_hostname }}
