---
# Source: homebox/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: homebox
  labels:
    helm.sh/chart: homebox-0.1.2
    app.kubernetes.io/name: homebox
    app.kubernetes.io/instance: homebox
    app.kubernetes.io/version: "0.20.2"
    app.kubernetes.io/managed-by: Helm
automountServiceAccountToken: true
