---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: channels
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt"
spec:
  tls:
    - hosts:
      - "channels.k.oneill.net"
      secretName: "channels-tls"
  rules:
    - host: "channels.k.oneill.net"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: channels
                port:
                  number: 8089
