---
apiVersion: v1
kind: Service
metadata:
  name: channels
  annotations:
    metallb.universe.tf/allow-shared-ip: channels
spec:
  type: LoadBalancer
  loadBalancerIP: 172.19.74.23
  ports:
  - port: 8089
    targetPort: 8089
    protocol: TCP
  selector:
    app: channels
