---
- name: "apt-get update"
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: "Remove unwanted packages"
  apt:
    name: "{{ packages_to_remove }}"
    state: absent

- name: "Install wanted packages"
  apt:
    name: "{{ packages_to_install }}"
    state: present
    autoremove: yes

- name: "Install non-free on Debian"
  apt:
    name: firmware-misc-nonfree
    state: present
  when: ansible_distribution == 'Debian'

- name: "Turn on passwordless sudo for sudo group"
  lineinfile:
      dest: /etc/sudoers
      state: present
      regexp: '^%sudo'
      line: '%sudo ALL=(ALL) NOPASSWD: ALL'

- name: "Setup ssh authorized keys for root"
  authorized_key:
    user: root
    key: "{{ item }}"
  loop: "{{ ssh_keys }}"
