---
- name: "apt-get update"
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600

- name: "Remove unwanted packages"
  ansible.builtin.apt:
    name: "{{ common_packages_to_remove }}"
    state: absent

- name: "Install wanted packages"
  ansible.builtin.apt:
    name: "{{ common_packages_to_install }}"
    state: present
    autoremove: true

- name: "Install non-free on Debian"
  ansible.builtin.apt:
    name: firmware-misc-nonfree
    state: present
  when: ansible_distribution == 'Debian'

- name: "Turn on passwordless sudo for sudo group"
  ansible.builtin.lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: "^%sudo"
    line: "%sudo ALL=(ALL) NOPASSWD: ALL"

- name: "Setup ssh authorized keys for root"
  ansible.posix.authorized_key:
    user: root
    key: "{{ item }}"
  loop: "{{ ssh_keys }}"
