---
# Source: vpa/templates/admission-controller-cleanup.yaml
apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: true
metadata:
  annotations:
    "helm.sh/hook": "post-delete"
    "helm.sh/hook-delete-policy": "hook-succeeded,before-hook-creation,hook-failed"
    "helm.sh/hook-weight": "-100"
  name: vpa-cleanup
  namespace: default
---
# Source: vpa/templates/admission-controller-cleanup.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vpa-cleanup
  labels:
    app.kubernetes.io/name: vpa
    helm.sh/chart: vpa-1.7.5
    app.kubernetes.io/instance: vpa
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: cleanup
  annotations:
    "helm.sh/hook": "post-delete"
    "helm.sh/hook-delete-policy": "hook-succeeded,before-hook-creation,hook-failed"
    "helm.sh/hook-weight": "-90"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: vpa-cleanup
    namespace: default
---
# Source: vpa/templates/admission-controller-cleanup.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: vpa-cleanup
  namespace: default
  labels:
    app.kubernetes.io/name: vpa
    helm.sh/chart: vpa-1.7.5
    app.kubernetes.io/instance: vpa
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: cleanup
  annotations:
    "helm.sh/hook": "post-delete"
    "helm.sh/hook-delete-policy": "hook-succeeded,before-hook-creation"
    "helm.sh/hook-weight": "-70"
spec:
  template:
    metadata:
      name: vpa-cleanup
      labels:
        app.kubernetes.io/name: vpa
        helm.sh/chart: vpa-1.7.5
        app.kubernetes.io/instance: vpa
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/component: cleanup
    spec:
      restartPolicy: Never
      serviceAccountName: vpa-cleanup
      containers:
      - name: cleanup
        image: quay.io/reactiveops/ci-images:v11-alpine
        command: ["bash"]
        args:
          - -c
          - |
            # From https://github.com/kubernetes/autoscaler/blob/vertical-pod-autoscaler-0.8.0/vertical-pod-autoscaler/pkg/admission-controller/delete-webhook.sh
            echo "Unregistering VPA admission controller webhook"
            kubectl delete -n default mutatingwebhookconfiguration.v1beta1.admissionregistration.k8s.io vpa-webhook-config || true
            kubectl delete -n default secret vpa-tls-certs || true
