---
# Source: vpa/templates/recommender-service-account.yaml
apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: true
metadata:
  name: vpa-recommender
  namespace: default
  labels:
    helm.sh/chart: vpa-1.7.5
    app.kubernetes.io/name: vpa
    app.kubernetes.io/instance: vpa
    app.kubernetes.io/version: "0.13.0"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: recommender
