---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kube-system

resources:
 - deployment.yaml
 - service.yaml
 - rbac.yaml
 - default-backend.yaml
 - default-backend-service.yaml

commonLabels:
  app: nginx-ingress
