---
- name: client | generate ssh key for this machine
  user:
    name: "{{ restic_client_user }}"
    generate_ssh_key: true
    ssh_key_file: "{{ restic_ssh_key }}"
    ssh_key_bits: "{{ restic_ssh_key_bits }}"
    ssh_key_type: "{{ restic_ssh_key_type }}"

- name: client | fetch ssh-key
  command: "cat {{ restic_ssh_key }}.pub"
  register: sshkey
  changed_when: false

- name: client | disable strict key checking for backup servers
  blockinfile:
    dest: "~{{ restic_client_user }}/.ssh/config"
    create: true
    marker: "### {mark} ANSIBLE MANAGED BLOCK for restic: {{ item.fqdn }} ###"
    content: |
      Host {{ item.fqdn }}
        StrictHostKeyChecking no
        IdentityFile {{ restic_ssh_key }}
        {% if item.port is defined %}
        Port {{ item.port }}
        {% endif %}
  with_items: "{{ restic_sftp_servers }}"

- name: client | put sshpubkey on the normal backupserver
  authorized_key:
    user: "{{ item.user }}"
    key: "{{ sshkey.stdout }}"
  delegate_to: "{{ item.fqdn }}"
  with_items: "{{ restic_sftp_servers }}"

