---
#restic_passphrase: <set password in config>

resticprofile_version: "0.21.0"
resticprofile_arch: amd64
resticprofile_bin_dir: "/usr/local/bin"
resticprofile_tmp_dir: "/tmp/resticprofile-ansible"
resticprofile_sftp_server: false
resticprofile_sftp_client: false
resticprofile_rclone_client: false
resticprofile_sftp_servers: []
# description: backup user on the client
# type: string
resticprofile_client_user: root


# The following restic_* variables are used to configure restic itself, not the
# resticprofile role. We intentionally ignore the var-naming[no-role-prefix]
# linting rule for these variables.
restic_version: 0.15.2 # noqa: var-naming[no-role-prefix]
restic_arch: amd64 # noqa: var-naming[no-role-prefix]
restic_sftp_server: false # noqa: var-naming[no-role-prefix]
restic_sftp_client: false # noqa: var-naming[no-role-prefix]
restic_rclone_client: false # noqa: var-naming[no-role-prefix]
restic_sftp_servers: [] # noqa: var-naming[no-role-prefix]
restic_client_user: root # noqa: var-naming[no-role-prefix]

restic_ssh_key: "~{{ restic_client_user }}/.ssh/id_restic_{{ restic_ssh_key_type }}" # noqa: var-naming[no-role-prefix]
restic_ssh_key_bits: 2048 # noqa: var-naming[no-role-prefix]
restic_ssh_key_type: ed25519 # noqa: var-naming[no-role-prefix]
