---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: prometheus
  labels:
    stable.k8s.psg.io/kcm.class: "default"
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
    - hosts:
      - "prometheus.k.oneill.net"
      secretName: "prometheus-tls"
  rules:
    - host: "prometheus.k.oneill.net"
      http:
        paths:
          - path: /
            backend:
              serviceName: prometheus
              servicePort: 9090
