---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: authentik

resources:
 - templates/statefulset.yaml
 - templates/svc-headless.yaml
 - templates/svc.yaml

secretGenerator:
  - name: authentik-postgresql
    env: secret.txt
    type: Opaque

commonLabels:
  app: authentik-postgresql
