---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
 - deployment.yaml
 - pvc-config.yaml
 - pvc-dnsmasq.yaml
 - service.yaml
 - service-dns-tcp.yaml
 - service-dns-udp.yaml
 - ingress.yaml
 - externalsecret.yaml

commonLabels:
  app: pihole

