---
- name: "Add Intel APT repo"
  apt_repository:
    repo: "deb https://download.01.org/gfx/ubuntu/14.04/main trusty main"
  when: intel | default(False)

- name: "Download OpenPHT package"
  get_url:
    url: "https://github.com/RasPlex/OpenPHT/releases/download/v{{ openpht_version }}/openpht_{{ openpht_version }}-{{ ansible_distribution_release }}_amd64.deb"
    dest: "/root/openpht_{{ openpht_version }}-{{ ansible_distribution_release }}_amd64.deb"
    mode: "0644"

- name: "Install plexhometheater package"
  apt:
    deb: "/root/openpht_{{ openpht_version }}-{{ ansible_distribution_release }}_amd64.deb" 
    state: present
  notify: "restart openpht"

- name: "Shutdown old PHT if running"
  service:
    name: pht
    state: stopped
  failed_when: False

- name: "Delete old PHT startup file"
  file:
    name: /etc/init/pht.conf
    state: absent

  # This won't start until x11 is running   
- name: "Install PHT upstart file"
  copy:
    src: roles/plex-client/files/openpht.conf
    dest: /etc/init/openpht.conf
    owner: root
    group: root
    mode: 0644
  notify: "restart openpht"


