apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto
data:
  mosquitto.conf: |-
    allow_anonymous false
    connection_messages true
    log_timestamp true
    log_type all
    password_file /passwd/passwd
    persistence true
    persistence_location /mosquitto/data

    port 1883
    protocol mqtt

    listener 9001
    protocol websockets