---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default

resources:
 - deploy.yaml
 - pvc.yaml
 - service.yaml

commonLabels:
  app: mosquitto

configMapGenerator:
 - name: mosquitto
   files:
     - mosquitto.conf 

secretGenerator:
  - name: mosquitto
    files:
      - passwd=secret.txt
    type: Opaque
