groups:
  - name: alert.rules
    rules:
      - alert: ExporterDown
        expr: up == 0
        for: 5m
      - alert: CO2_PPM_Too_High
        expr: awair_sensor_co2 > 1000
        for: 5m
        annotations:
          message: "Open a window or door!"
      - alert: Netatmo_Battery_Low
        expr: netatmo_sensor_battery_percent < 20
        for: 2h
