---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: exporter
spec:
  replicas: 1
  template:
    metadata:
      name: awair-exporter
    spec:
      containers:
      - name: awair-exporter
        image: dvorak/awair_exporter
        imagePullPolicy: Always
        envFrom:
          - secretRef:
              name: exporter
        ports:
        - containerPort: 8000
