apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: awair-exporter
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: awair-exporter
  template:
    metadata:
      name: awair-exporter
      labels:
        app: awair-exporter
    spec:
      containers:
      - name: awair-exporter
        image: dvorak/awair_exporter
        imagePullPolicy: Always
        envFrom:
          - secretRef:
              name: awair-exporter
        ports:
        - containerPort: 8000
