apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: awair-exporter
spec:
  secretStoreRef:
    name: production
    kind: ClusterSecretStore
  refreshInterval: "1h"
  target:
    name: exporter
  dataFrom:
    - extract:
        key: awair-exporter
