---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
namePrefix: awair-
resources:
 - deploy.yaml
 - secret.yaml
 - service.yaml
commonLabels:
  app: awair-exporter