---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
namePrefix: awair-

resources:
 - deploy.yaml
 - service.yaml

commonLabels:
  app: awair-exporter

secretGenerator:
  - name: exporter
    env: secret.txt
    type: Opaque
