---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kube-flannel

resources:
- namespace.yaml
- helm/templates/config.yaml
- helm/templates/daemonset.yaml
- helm/templates/rbac.yaml
- helm/templates/serviceaccount.yaml
