---
galaxy_info:
  author: Michaël Rigart
  role_name: interfaces
  description: An ansible role for configuring different network interfaces.
  company: Netronix.be
  license: GPLv3
  min_ansible_version: 2.2
  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all
    - name: EL
      versions:
        - all
    - name: Fedora
      versions:
        - all
  galaxy_tags:
    - system
dependencies: []
