---
prometheus:
  scrapeAnnotations: true
  metricsPort: 7472

controller:
  tolerations:
  - key: node-role.kubernetes.io/master
    operator: Exists
    effect: NoSchedule
  - key: node-role.kubernetes.io/control-plane
    operator: Exists
    effect: NoSchedule

speaker:
  podAnnotations:
    prometheus.io/port: '7472'
