---
# Source: goldilocks/templates/controller-serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: goldilocks-controller
  labels:
    app.kubernetes.io/name: goldilocks
    helm.sh/chart: goldilocks-6.1.3
    app.kubernetes.io/instance: goldilocks
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: controller
