---
# Source: goldilocks/templates/controller-clusterrolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: goldilocks-controller
  labels:
    app.kubernetes.io/name: goldilocks
    helm.sh/chart: goldilocks-6.1.3
    app.kubernetes.io/instance: goldilocks
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: goldilocks-controller
subjects:
  - kind: ServiceAccount
    name: goldilocks-controller
    namespace: default
