---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: octobox-postgresql
  labels:
    k8s-app: octobox-postgresql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
