# Source: loki/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: loki
  namespace: default
  labels:
    chart: loki-2.16.0
    release: loki
    heritage: Helm
    app.kubernetes.io/name: "loki"
    app.kubernetes.io/instance: "loki"
  annotations: {}
spec:
  type: ClusterIP
  ports:
    - port: 3100
      protocol: TCP
      name: http-metrics
      targetPort: http-metrics
  selector:
    release: loki
    app.kubernetes.io/name: "loki"
    app.kubernetes.io/instance: "loki"
