# Source: loki/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    chart: loki-2.16.0
    release: loki
    heritage: Helm
    app.kubernetes.io/name: "loki"
    app.kubernetes.io/instance: "loki"
  annotations: {}
  name: loki
  namespace: default
automountServiceAccountToken: true
