---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: smokeping
  labels:
    app: smokeping
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt"
spec:
  tls:
    - hosts:
      - "smokeping.k.oneill.net"
      secretName: "smokeping-tls"
  rules:
    - host: "smokeping.k.oneill.net"
      http:
        paths:
          - path: /
            backend:
              serviceName: smokeping
              servicePort: 80
