---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: smokeping-config
  labels:
    k8s-app: smokeping
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: smokeping-data
  labels:
    k8s-app: smokeping
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi


