---
- name: "apt-get update"
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: "Install boto3"
  apt:
    name: "python3-boto3"
    state: present

- name: "Include mprahl.lets-encrypt-route-53"
  ansible.builtin.include_role:
    name: mprahl.lets-encrypt-route-53
