---
- name: Restart peanut containers
  community.docker.docker_compose_v2:
    project_src: /etc/nut/peanut
    state: restarted
    wait: true
  environment:
    AWS_ACCESS_KEY_ID: "{{ ler53_aws_access_key }}"
    AWS_SECRET_ACCESS_KEY: "{{ ler53_aws_secret_key }}"
    AWS_REGION: "{{ route53_region }}"
  become: true
