---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: plexmediaserver
  labels:
    k8s-app: plexmediaserver
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        k8s-app: plexmediaserver
    spec:
      containers:
      - name: plexmediaserver
        image: plexinc/pms-docker:plexpass
        imagePullPolicy: Always
        ports:
          # See
          # https://support.plex.tv/hc/en-us/articles/201543147-What-network-ports-do-I-need-to-allow-through-my-firewall
          # for port details
        - containerPort: 32400
        - containerPort: 1900
          protocol: "UDP"
        - containerPort: 32410
          protocol: "UDP"
        - containerPort: 32412
          protocol: "UDP"
        - containerPort: 32413
          protocol: "UDP"
        - containerPort: 32414
          protocol: "UDP"
        env:
          - name: HOSTNAME
            value: "kube-pms"
          - name: TZ
            value: "EST5EDT"
          - name: DEBUG
            value: "true"
          - name: PLEX_CLAIM
            valueFrom:
              secretKeyRef:
                name: plexmediaserver
                key: PLEX_CLAIM
        volumeMounts:
          - mountPath: "/config"
            name: config
          - mountPath: "/transcode"
            name: transcode
          - mountPath: "/data"
            name: video
      volumes:
        - name: config
          iscsi:
            targetPortal: 172.19.74.139
            iqn: iqn.2000-01.com.synology:fs2.plex-config.11cf152a97
            lun: 1
            fsType: ext4
            chapAuthDiscovery: false
            chapAuthSession: true
            secretRef:
              name: plex-chap-secret
        - name: transcode
          persistentVolumeClaim:
            claimName: plexmediaserver-transcode
        - nfs:
            server: fs1.oneill.net
            path: /volume1/shared/video
          name: video
