---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: plexmediaserver
  labels:
    k8s-app: plexmediaserver
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt"
spec:
  tls:
    - hosts:
      - "plex.k.oneill.net"
      secretName: "plexmediaserver-tls"
  rules:
    - host: "plex.k.oneill.net"
      http:
        paths:
          - path: /
            backend:
              serviceName: plexmediaserver
              servicePort: 32400
