---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
 - deploy.yaml
 - ingress.yaml
 - pvc.yaml
 - service.yaml

commonLabels:
  app: plexmediaserver

secretGenerator:
  - name: plexmediaserver
    env: secret.txt
    type: Opaque
  - name: plex-chap-secret
    env: iscsi-secret.txt
    type: kubernetes.io/iscsi-chap
