---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: plexmediaserver-config
  labels:
    k8s-app: plexmediaserver
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: plexmediaserver-transcode
  labels:
    k8s-app: plexmediaserver
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
