---
apiVersion: v1
kind: Service
metadata:
  name: plexmediaserver
  labels:
    k8s-app: plexmediaserver
spec:
  ports:
  - port: 32400
    targetPort: 32400
    protocol: TCP
  selector:
    k8s-app: plexmediaserver
