apiVersion: v1
kind: ConfigMap
metadata:
  name: rclone-config
data:
  rclone.conf: |-
    # Encrypted rclone configuration File

    RCLONE_ENCRYPT_V0:
    dPbLuKBx4e4aM31MIsXj84gWsnTR2jpcc77KdLe0hYiyIL+pQRNeg7Ag8x5DnVnIl1tL81Lxa3AW/DVyyCJGPtyn5OSB3JN9n48N+nVc/lW5xkhflclUv8pPatLxzXr9JdETz8v53DY8rP+M7ypV+v3kh6wCCbihBzeXvCV8g25UQGmyjTq7w3awvxHQ980j8dsgV+27t89m8srIcOF8GFTP9zr9b72HwdjtT3+Ii0APARBKyUGezNfnQ9vAHIL2o9OJODA9tlA3i0ulmBmlM+BB62Mul2TLlMUoeg1zKnQ4Ufh/5FRlFATQnl5G5OSwSo3U9hnnRN4p9AkIz3ZgjudjBXdyrUU9L3OOm2CIIUfX9rGeXAFdlCSfvpHPqlQFDW4j8I9RYT8erlcf1PRNHZeVhLVOI3CfLvCUbTrx36KIunJ0Em/AVuDLLt1lg6oanY7+PEkcifEr811Pj211WPyxcOzSzxfybgR5dha3sv+4M5l735udGoazmrDQ1teW6JBrRJamP6Rt6o5+aFSOfc6ZbRHqSx0aGg6aZCp+mYzl4o3v5GGLw0blJ8iffB7uX67Z3olNyT3A1+aXxza7xSs3i6jcVBQK58uxXjeN8l/o70FL6c3rAazFr7R92iWMj6aq49XtPb+UUeXXgVzeojvyxBYh3jp67eXKmrVkgdWRI/OcHpbkyOD3T/2D8mcX6C+snJB4YPMdcBEvNGPoWEqrdxhzFG8sVhL2Fjc0224Q+JtwOCci18wzi63ia9IEpRqlNtxy7jPuwO8AvggJpzt3G13hC+jijy/J/RkRC9d1Hs0TAnMVo4FWX3f0NNOzMQRd/62mvaKoEQFaBKDhjB26amaYdDGNzOtI/0Y9FNwMmncjXNCcy9DMBg9+anLnDwCiUut1FZp3qsvjAd0VkgYh3kFWdMpC8b8UtWoDsZVwJtAvdWVjNd94cJb9DzYbZyQKPHjHWzSwVh2gsHeVJAvgNT2UWTIRTV8cxf+XZ1122oxOiuZ4PLa5k3Wi3RQ8kDfyqXJDq8a6Q6gQYQv9RdtVrZ2hnkShHdXzZ5Q=
