apiVersion: batch/v1
kind: CronJob
metadata:
  name: rclone-sync-k8s-pv
spec:
  schedule: "0 0/4 * * * "
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 300
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: rclone
            command:
              - /run-rclone.sh
              - sync
              - --drive-chunk-size=128M
              - --transfers=2
              - --links
              - --fast-list
              - /source
              - gsc:k8s-pv
              - -v
              - --stats=15s
              - "--bwlimit=3M"
            image: ghcr.io/claytono/rclone:latest
            imagePullPolicy: Always
            env:
            - name: RCLONE_CONFIG_PASS
              valueFrom:
                secretKeyRef:
                  name: rclone-config-password
                  key: RCLONE_CONFIG_PASS
            - name: PUSH_GATEWAY
              value: https://pushgateway.k.oneill.net
            - name: INSTANCE
              value: k8s-pv
            - name: LANG
              value: "en_US.UTF-8"
            - name: LANGUAGE
              value: en_US.UTF-8
            - name: LC_ALL
              value: en_US.UTF-8
            volumeMounts:
            - mountPath: /root/.config/rclone
              name: rclone-config
            - mountPath: /source
              name: source
              readOnly: true
          volumes:
          - name: rclone-config
            configMap:
              name: rclone-config
          - nfs:
              server: fs2.oneill.net
              path: /volume1/k8s-pv
              readOnly: true
            name: source
