---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: kibana
  namespace: kube-system
  labels:
    stable.k8s.psg.io/kcm.class: "default"
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
    - hosts:
      - "kibana.k.oneill.net"
      secretName: "kibana-tls"
  rules:
    - host: "kibana.k.oneill.net"
      http:
        paths:
          - path: /
            backend:
              serviceName: kibana-logging
              servicePort: 5601
