---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: es-persistent-storage
  namespace: kube-system
  labels:
    k8s-app: elasticsearch-logging
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 250Gi


