---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: pushgateway
  namespace: kube-system
  labels:
    k8s-app: pushgateway
    stable.k8s.psg.io/kcm.class: "default"
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
    - hosts:
      - "pushgateway.k.oneill.net"
      secretName: "pushgateway-tls"
  rules:
    - host: "pushgateway.k.oneill.net"
      http:
        paths:
          - path: /
            backend:
              serviceName: pushgateway
              servicePort: 9091
