---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: authentik

resources:
- templates/master/service.yaml
- templates/master/statefulset.yaml
- templates/configmap.yaml
- templates/headless-svc.yaml
- templates/health-configmap.yaml
- templates/scripts-configmap.yaml
- templates/serviceaccount.yaml

commonLabels:
  app: authentik-redis
