---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cross-seed
  labels:
    app: cross-seed
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt
    gethomepage.dev/enabled: 'true'
    gethomepage.dev/name: cross-seed
    gethomepage.dev/description: TV Manager
    gethomepage.dev/group: Media
    gethomepage.dev/icon: cross-seed.png
spec:
  tls:
  - hosts:
    - cross-seed.k.oneill.net
    secretName: cross-seed-tls
  rules:
  - host: cross-seed.k.oneill.net
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: cross-seed
            port:
              number: 2468
