---

interfaces_pkgs:
  debian:
    - python{% if ansible_facts.python.version.major >= 3 %}3{% endif %}-selinux
    - bridge-utils
    - ifenslave
    - ifupdown
    - iproute2
    - resolvconf
  redhat:
    '7':
      - libselinux-python
      - bridge-utils
      - iproute
      - iputils
    '8':
      - dhcp-client
      - iproute
      - iputils
      - network-scripts
interfaces_net_path:
  debian: /etc/network/interfaces.d
  redhat: /etc/sysconfig/network-scripts
interfaces_pkg_state: present
interfaces_route_tables: []
interfaces_ether_interfaces: []
interfaces_bridge_interfaces: []
interfaces_bond_interfaces: []
interfaces_workaround_centos_remove:
  - ens3
  - ens3-1
  - eth0
interfaces_pause_time: 0
interfaces_setup_filter: "{{ omit }}"
interfaces_setup_gather_subset: "{{ omit }}"
interfaces_bond_setup_slaves: true
