---
interfaces_use_networkmanager: "{{ ansible_facts.os_family == 'RedHat' and ansible_facts.distribution_major_version | int >= 9 }}"
interfaces_use_nmconnection: "{{ ansible_facts.os_family == 'RedHat' and ansible_facts.distribution_major_version | int >= 9 }}"

interfaces_pkg_state: present
interfaces_route_tables: []
interfaces_ether_interfaces: []
interfaces_bridge_interfaces: []
interfaces_bond_interfaces: []
interfaces_workaround_centos_remove:
  - ens3
  - ens3-1
  - eth0
interfaces_pause_time: 0
interfaces_setup_filter: "{{ omit }}"
interfaces_setup_gather_subset: "{{ omit }}"
interfaces_bond_setup_slaves: true
interfaces_merge: false
interfaces_bounce_ignore_errors: false
