---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: infinitude-state
  labels:
    app: infinitude-state
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
