---
- name: install pkg
  apt:
    name: 'chrony'
    state: present
  tags: [ ntp, chrony ]

- name: copy conf
  template:
    src: '{{ item.name }}.j2'
    dest: '/etc/chrony/{{ item.name }}'
    mode: '{{ item.mode }}'
  loop:
    - { name: chrony.conf, mode: '0644' }
    - { name: chrony.keys, mode: '0640' }
  notify: restart chrony
  tags: [ ntp, chrony ]

- name: enable ufw
  ufw:
    comment: 'NTP server port'
    rule: allow
    direction: in
    proto: udp
    port: '123'
    src: '{{ item }}'
  when:
    - enable_ufw | bool
    - ansible_fqdn in ntp_servers
  loop: '{{ lan_addr }}'
  tags: [ ntp, chrony ]

- name: enable&start service
  service:
    name: chrony
    enabled: True
    state: started
  tags: [ ntp, chrony ]

...
