---
- name: TEMP | Prepare
  hosts: instance
  gather_facts: true
  tasks:
    # https://github.com/geerlingguy/docker-rockylinux9-ansible/issues/6#issuecomment-2805378491
    # https://github.com/geerlingguy/docker-fedora41-ansible/issues/2
    - name: TEMP | Fix due to PAM error in some upstream images
      when: ansible_distribution == 'Fedora' or ansible_distribution == 'Rocky'
      # Explicitly don't try to become because that will trigger the broken PAM error
      # become: true
      # Bug in some upstream distros, /etc/shadow has no file perms in container image
      ansible.builtin.file:
        path: /etc/shadow
        mode: '400'

- name: Prepare
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Create Headscale user
      community.docker.docker_container_exec:
        container: headscale
        command: headscale users create test

    - name: Create preauth key
      community.docker.docker_container_exec:
        container: headscale
        command: headscale preauthkeys create -u test --reusable

    - name: Fetch Headscale container info
      community.docker.docker_container_info:
        name: headscale
      register: headscale_info

    - name: Fetch Headscale network info
      community.docker.docker_network_info:
        name: headscale
      register: headscale_network

    - name: Get instance names
      ansible.builtin.set_fact:
        instance_names: "{{ headscale_network.network.Containers | dict2items | selectattr('value.Name', 'match', '^instance') | map(attribute='value.Name') | list }}"

    - name: Set hosts override for Headscale
      delegate_to: "{{ item }}"
      loop: "{{ instance_names }}"
      ansible.builtin.lineinfile:
        path: /etc/hosts
        line: "{{ headscale_info.container.NetworkSettings.Networks.headscale.IPAddress }}  headscale"
        unsafe_writes: true  # Hosts file in the docker container can't be written to atomically
