---
- name: "apt-get update"
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: "Remove unwanted packages"
  apt:
    name: "{{ item }}"
    state: absent
  with_items: "{{ packages_to_remove }}"

- name: "Remove unwanted packages"
  apt:
    name: "{{ item }}"
    state: present
  with_items: "{{ packages_to_install }}"
