---
- hosts: all
  gather_facts: no
  tasks:
    - include_vars: vars/vault.yaml

  roles:
    - role: install_python
      when: "setup_upgrade | default(false) | bool"
      tags: setup_upgrade

- hosts: all
  roles:
    - role: setup_upgrade
      when: "setup_upgrade | default(false) | bool"
      tags: setup_upgrade

- hosts: all
  roles:
    - role: common
    - role: layereight.wifi
      when: "wifi_ssid is defined"
      tags: [wifi, network]
    - role: MichaelRigart.interfaces
      become: true
      tags: network
      when: "manage_network | default(false) | bool"

- hosts: all
  roles:
    - ANXS.generic-users
  tasks:
    - name: Get user groups
      getent:
        database: group

    - name: Add coneill to groups if they exist
      user: name="coneill" groups="{{item}}" append=yes
      when: item in ansible_facts.getent_group
      with_items:
       - libvirt

- hosts: all
  roles:
    - tbaczynski.chrony
    - role: Yannik.relaymail
      when: is_vagrant is undefined or not is_vagrant
    - role: resticprofile
      tags: restic

- hosts: certbot
  become: True
  roles:
    - role: certbot
      tags: certbot

- hosts: nut
  roles:
    - role: nut
      tags: nut

- hosts: kubernetes
  tasks:
  - name: "Create containerd package pin for version"
    copy:
      dest: "/etc/apt/preferences.d/containerd"
      content: |
        Package: containerd.io
        Pin: version {{ containerd_version }}
        Pin-Priority: 900
    when: containerd_version is defined

- hosts: kubernetes
  roles:
    - role: geerlingguy.containerd
      tags: containerd

- hosts: all,!tailscale_disabled
  roles:
    - role: artis3n.tailscale
      tags: tailscale
  tasks:
    - name: "Configure sysctl for tailscale ip forwarding"
      copy:
        dest: /etc/sysctl.d/99-kubernetes-cri.conf
        content: |
          net.ipv4.ip_forward=1
          net.ipv6.conf.all.forwarding=1
      register: sysctl_file
      when: ip_forwarding_enabled | default(false) | bool
      tags: tailscale

    - name: "Reload sysctl for tailscale ip forwarding"
      command: sysctl --system
      when: sysctl_file.changed
      tags: tailscale

- hosts: kubernetes
  roles:
    - role: kubeadm
      tags: kubernetes

- hosts: all
  roles:
    - role: UnderGreen.prometheus-node-exporter
      tags: prom
      when: "node_exporter_enabled | default(false)"
