---
- name: Install Python if needed
  hosts: all
  gather_facts: false

  roles:
    - role: install_python
      when: "setup_upgrade | default(false) | bool"
      tags: setup_upgrade

- name: System upgrade
  hosts: all
  roles:
    - role: setup_upgrade
      when: "setup_upgrade | default(false) | bool"
      tags: setup_upgrade

- name: Common and network roles
  hosts: all
  roles:
    - role: common
    - role: layereight.wifi
      when: "wifi_ssid is defined"
      tags: [wifi, network]
    - role: michaelrigart.interfaces
      become: true
      tags: network
      when: "manage_network | default(false) | bool"

- name: User group management
  hosts: all
  roles:
    - anxs.generic-users
  tasks:
    - name: Get user groups
      ansible.builtin.getent:
        database: group

    - name: Add coneill to groups if they exist
      ansible.builtin.user:
        name: "coneill"
        groups: "{{ item }}"
        append: true
      when: item in ansible_facts.getent_group
      loop:
        - libvirt

- name: Chrony, relaymail, and resticprofile
  hosts: all
  roles:
    - tbaczynski.chrony
    - role: yannik.relaymail
      when: is_vagrant is undefined or not is_vagrant
    - role: resticprofile
      tags: restic

- name: Certbot
  hosts: certbot
  become: true
  roles:
    - role: certbot
      tags: certbot

- name: NUT
  hosts: nut
  roles:
    - role: nut
      tags: nut

- name: Tailscale sysctl config
  hosts: all,!tailscale_disabled
  roles:
    - role: artis3n.tailscale.machine
      tags: tailscale
  tasks:
    - name: "Configure sysctl for tailscale ip forwarding"
      ansible.builtin.copy:
        dest: /etc/sysctl.d/99-kubernetes-cri.conf
        content: |
          net.ipv4.ip_forward=1
          net.ipv6.conf.all.forwarding=1
        mode: "0644"
      register: sysctl_file
      when: ip_forwarding_enabled | default(false) | bool
      tags: tailscale
      notify: Reload sysctl for tailscale ip forwarding

  handlers:
    - name: Reload sysctl for tailscale ip forwarding
      ansible.builtin.command: sysctl --system
      when: sysctl_file.changed
      tags: tailscale

- name: Kubernetes role
  hosts: kubernetes
  roles:
    - role: kubeadm
      tags: kubernetes

- name: Prometheus node exporter
  hosts: all
  roles:
    - role: undergreen.prometheus-node-exporter
      tags: prom
      when: "node_exporter_enabled | default(false)"
