# This filename is prefixed with 0 because kubeadm apply -R -f processes files
# in filename order.
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: nfs # or choose another name, must match deployment's env PROVISIONER_NAME'
parameters:
  archiveOnDelete: "false"
  onDelete: "retain"
  pathPattern: "${.PVC.namespace}-${.PVC.name}"
