---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system

resources:
 - storageclass.yaml
 - rbac.yaml
 - deployment.yaml

commonLabels:
  app: nfs-subdir-external-provisioner

