---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: unpoller
spec:
  replicas: 1
  template:
    metadata:
      name: unpoller
    spec:
      containers:
      - name: unpoller
        image: ghcr.io/unpoller/unpoller:latest
        args:
          - --config
          - /config/up.conf
        ports:
        - name: web
          containerPort: 9130
        env:
        - name: UP_UNIFI_DEFAULT_PASS
          valueFrom:
            secretKeyRef:
              name: unpoller
              key: cloudkey_password
        volumeMounts:
        - name: config
          mountPath: /config
      volumes:
      - name: config
        configMap:
          name: unpoller