---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
 - deploy.yaml
 - service.yaml

commonLabels:
  app: unpoller

configMapGenerator:
 - name: unpoller
   files:
     - up.conf

secretGenerator:
  - name: unpoller
    env: secret.txt
    type: Opaque