apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: 'true'
  name: unpoller
spec:
  selector:
    app: unpoller
  ports:
  - name: unpoller
    protocol: TCP
    port: 9130
