apiVersion: batch/v1
kind: CronJob
metadata:
  name: resticprofile-azure
spec:
  schedule: "4 18 * * *"
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 300
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            resticprofile: "azure"
          annotations:
            prometheus.io/scrape: "true"
            prometheus.io/path: "/metrics"
            prometheus.io/port: "5572"
        spec:
          hostname: rp-kube
          restartPolicy: OnFailure
          initContainers:
            - name: generate-uuid
              image: alpine
              command: ['sh', '-c', 'apk add --no-cache util-linux; uuidgen >/tmp/uuid']
              volumeMounts:
                - mountPath: /tmp
                  name: scratch
          containers:
          - name: resticprofile
            command:
              - resticprofile
              - -c
              - /resticprofile-config/profiles.yaml
              - -n
              - azure
              - --lock-wait
              - 1h
              - backup
            image: creativeprojects/resticprofile
            imagePullPolicy: IfNotPresent
            env:
              - name: RESTIC_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: resticprofile
                    key: RESTIC_PASSWORD
              - name: RESTIC_FROM_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: resticprofile
                    key: RESTIC_PASSWORD
              - name: RESTIC_PASSWORD2
                valueFrom:
                  secretKeyRef:
                    name: resticprofile
                    key: RESTIC_PASSWORD
            volumeMounts:
            - mountPath: /rclone-config
              name: rclone-config
            - mountPath: /resticprofile-config
              name: resticprofile-config
            - mountPath: /tmp
              name: scratch
            - mountPath: /cache
              name: cache
            - mountPath: /source/k8s-pv
              name: k8s-pv
              readOnly: true
            - mountPath: /source/backups
              name: backups
              readOnly: true
            - mountPath: /source/shared
              name: shared
              readOnly: true
          volumes:
          - name: rclone-config
            secret:
              secretName: resticprofile-rclone-config
              items:
              - key: rclone-config-secret.txt
                path: rclone.conf
          - name: resticprofile-config
            configMap:
              name: resticprofile-config
          - name: scratch
            emptyDir: {}
          - name: cache
            persistentVolumeClaim:
              claimName: resticprofile-cache-synology
          - nfs:
              server: fs2.oneill.net
              path: /volume1/k8s-pv
              readOnly: true
            name: k8s-pv
          - nfs:
              server: fs2.oneill.net
              path: /volume2/backups
              readOnly: true
            name: backups
          - nfs:
              server: fs2.oneill.net
              path: /volume2/shared
              readOnly: true
            name: shared
