apiVersion: batch/v1
kind: CronJob
metadata:
  name: resticprofile-copy
spec:
  schedule: "0 * * * *"
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 300
  jobTemplate:
    spec:
      template:
        spec:
          hostname: rp-kube
          restartPolicy: OnFailure
          securityContext:
            runAsUser: 10007
            runAsGroup: 10007
          containers:
          - name: resticprofile
            command:
              - resticprofile
              - -c
              - /resticprofile-config/profiles.yaml
              - -n 
              - copy-main
              - --lock-wait
              - 1h
              - copy
            image: creativeprojects/resticprofile
            imagePullPolicy: IfNotPresent
            env:
              - name: RESTIC_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: resticprofile
                    key: RESTIC_PASSWORD
              - name: RESTIC_FROM_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: resticprofile
                    key: RESTIC_PASSWORD
              - name: RESTIC_PASSWORD2
                valueFrom:
                  secretKeyRef:
                    name: resticprofile
                    key: RESTIC_PASSWORD
            volumeMounts:
            - mountPath: /rclone-config
              name: rclone-config
            - mountPath: /resticprofile-config
              name: resticprofile-config
            - mountPath: /tmp
              name: scratch
            - mountPath: /cache
              name: cache
            - mountPath: /source/backups/restic/repos
              name: backups
          volumes:
          - name: rclone-config
            secret:
              secretName: resticprofile-rclone-config
              items:
              - key: rclone-config-secret.txt
                path: rclone.conf
          - name: resticprofile-config
            configMap:
              name: resticprofile-config
          - name: scratch
            emptyDir: {}
          - name: cache
            persistentVolumeClaim:
              claimName: resticprofile-cache-copy
          - nfs:
              server: fs2.oneill.net
              path: /volume2/backups/restic/repos
            name: backups
