apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: resticprofile
spec:
  secretStoreRef:
    name: production
    kind: ClusterSecretStore
  refreshInterval: "1h"
  dataFrom:
  - extract:
      key: resticprofile
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: resticprofile-rclone
spec:
  secretStoreRef:
    name: production
    kind: ClusterSecretStore
  refreshInterval: "1h"
  dataFrom:
  - extract:
      key: resticprofile-rclone
