---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- cronjob-copy-main.yaml
- cronjob-b2.yaml
- cronjob-b2-forget.yaml
- cronjob-migrate-azure-to-b2.yaml
- pvc.yaml
- externalsecret.yaml

configMapGenerator:
- files:
  - profiles.yaml
  name: resticprofile-config
  options:
    disableNameSuffixHash: true
- files:
  - rclone.conf
  name: rclone-config
  options:
    disableNameSuffixHash: true
labels:
- includeSelectors: true
  pairs:
    app: resticprofile
