---
default:
    repository: rclone:gsc:restic
    compression: max
#    initialize: true
    verbose: true
    pack-size: 64

    env:
        RCLONE_BWLIMIT: 3M
        RCLONE_CONFIG: /rclone-config/rclone.conf
        RESTIC_PROGRESS_FPS: "0.1"
        RESTIC_CACHE_DIR: "/cache"

    backup:
        source:
        - /source
        exclude:
        - /source/backup/borg
        - /source/backup/restic
    forget:
        keep-hourly: 24
        keep-daily: 14
        keep-monthly: 24
        keep-weekly: 12
        prune: true
    prometheus-labels:
    -   host: 'kubernetes'
    prometheus-push: https://pushgateway.k.oneill.net/
    retention:
        after-backup: true
        keep-hourly: 24
        keep-daily: 14
        keep-monthly: 24
        keep-weekly: 12
        prune: true
    check:
      read-data-subset: "50M"

copy-main:
    compression: max
    repository: /source/backups/restic/repos/main
    verbose: true
    pack-size: 64

    env:
        RCLONE_BWLIMIT: 3M
        RCLONE_CONFIG: /rclone-config/rclone.conf
        RESTIC_PROGRESS_FPS: "0.1"
        RESTIC_CACHE_DIR: "/cache"

    copy:
      repository: rclone:gsc:restic
    forget:
        keep-hourly: 24
        keep-daily: 14
        keep-monthly: 24
        keep-weekly: 12
        prune: true
    prometheus-labels:
    -   host: 'kubernetes'
    prometheus-push: https://pushgateway.k.oneill.net/
    retention:
        after-backup: true
        keep-hourly: 24
        keep-daily: 14
        keep-monthly: 24
        keep-weekly: 12
        prune: true
    check:
      read-data-subset: "50M"

