---
name: CI

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4

    - name: Install Nix & run pre-commit
      uses: cachix/install-nix-action@c134e4c9e34bac6cab09cf239815f9339aaaf84e  # v31
      with:
        github_access_token: ${{ github.token }}

    - name: Cache pre-commit
      uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684  # v4
      with:
        path: ~/.cache/pre-commit
        key: precommit-${{ hashFiles('.pre-commit-config.yaml') }}
        restore-keys: |
          precommit-

    - run: |-
        nix develop --command ./scripts/lint
