---
- name: Converge
  hosts: all
  tasks:
    - name: "Include artis3n.tailscale"
      ansible.builtin.include_role:
        name: artis3n.tailscale.machine
      vars:
        tailscale_up_skip: true
