---
apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: tautulli
  namespace: argocd

spec:
  project: default
  source:
    repoURL: https://github.com/claytono/infra.git
    targetRevision: main
    path: kubernetes/tautulli
  destination:
    server: https://kubernetes.default.svc
    namespace: default
