apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kube-cert-manager
  name: kube-cert-manager
  namespace: kube-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kube-cert-manager
      name: kube-cert-manager
    spec:
      serviceAccount: kube-cert-manager
      containers:
        - name: kube-cert-manager
          image: dvorak/kube-cert-manager:v0.4.0-24-gc8443d4
          args:
            - "-data-dir=/var/lib/cert-manager"
            #- "-acme-url=https://acme-staging.api.letsencrypt.org/directory"
            # NOTE: the URL above points to the staging server, where you won't get real certs.
            # Uncomment the line below to use the production LetsEncrypt server:
            - "-acme-url=https://acme-v01.api.letsencrypt.org/directory"
            # You can run multiple instances of kube-cert-manager for the same namespace(s),
            # each watching for a different value for the 'class' label
            #- "-class=default"
            # You can choose to monitor only some namespaces, otherwise all namespaces will be monitored
            #- "-namespaces=default,test"
            # If you set a default email, you can omit the field/annotation from Certificates/Ingresses
            - "-default-email=clayton@oneill.net"
            # If you set a default provider, you can omit the field/annotation from Certificates/Ingresses
            - "-default-provider=route53"
            # Renew right Lets Encrypt starts sending emails
            - "-renew-before-days=30"
          volumeMounts:
            - name: data
              mountPath: /var/lib/cert-manager
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: kube-cert-manager-dns-aws-creds
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: kube-cert-manager-dns-aws-creds
                  key: AWS_SECRET_ACCESS_KEY
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: kube-cert-manager-data
