---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: kube-cert-manager-data
  namespace: kube-system
  labels:
    k8s-app: kube-cert-manager
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
