---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: autobrr
  labels:
    app: autobrr
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt
    gethomepage.dev/enabled: 'true'
    gethomepage.dev/name: autobrr
    gethomepage.dev/description: TV Manager
    gethomepage.dev/group: Media
    gethomepage.dev/icon: autobrr.png
spec:
  tls:
  - hosts:
    - autobrr.k.oneill.net
    secretName: autobrr-tls
  rules:
  - host: autobrr.k.oneill.net
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: autobrr
            port:
              number: 7474
