---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: transmission
spec:
  secretStoreRef:
    name: production
    kind: ClusterSecretStore
  refreshInterval: 1h
  dataFrom:
  - extract:
      key: transmission
