---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
 - cronjob-full.yaml
 - cronjob-incremental.yaml
 - externalsecret.yaml
 - pvc.yaml

commonLabels:
  app: got-your-back

configMapGenerator:
  - name: run-script
    files:
      - run.sh

