---
# Source: homebox/charts/postgresql/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: homebox-postgresql
  namespace: "default"
  labels:
    app.kubernetes.io/instance: homebox
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/version: 17.5.0
    helm.sh/chart: postgresql-16.7.13
automountServiceAccountToken: false
