---
- name: Install runc (OCI runtime)
  ansible.builtin.include_role:
    name: githubixx.runc

- name: Install containerd
  ansible.builtin.include_role:
    name: githubixx.containerd

- name: Include common tasks
  ansible.builtin.include_tasks: common.yaml
- name: Include iscsi tasks
  ansible.builtin.include_tasks: iscsi.yaml
- name: Include master tasks
  ansible.builtin.include_tasks: master.yaml
  when: is_kubernetes_master
- name: Include node tasks
  ansible.builtin.include_tasks: nodes.yaml
  when: is_kubernetes_node
