---
- name: "Reset kubeadm if requested"
  ansible.builtin.command: "kubeadm reset"
  when: "kubeadm_reset |default(false) |bool"

- name: "Copy over kubeadm config file"
  ansible.builtin.template:
    src: "templates/kubeadm.conf.j2"
    dest: "/root/kubeadm.conf"
    owner: root
    group: root
    mode: "0644"

- name: "Kubeadm init"
  ansible.builtin.command: "kubeadm init --config /root/kubeadm.conf"
  args:
    creates: "/etc/kubernetes/admin.conf"

- name: "Set KUBECONFIG for root"
  ansible.builtin.lineinfile:
    path: "/root/.bashrc"
    line: "export KUBECONFIG=/etc/kubernetes/super-admin.conf"
    regexp: "^export KUBECONFIG="

- name: "Fixup admin.conf to use fqdn"
  ansible.builtin.lineinfile:
    path: "/etc/kubernetes/admin.conf"
    regexp: "^(\\s+)server:\\s+"
    backrefs: true
    line: "\\1server: https://{{ ansible_fqdn }}:6443"

- name: "Fixup super-admin.conf to use fqdn"
  ansible.builtin.lineinfile:
    path: "/etc/kubernetes/super-admin.conf"
    regexp: "^(\\s+)server:\\s+"
    backrefs: true
    line: "\\1server: https://{{ ansible_fqdn }}:6443"

- name: "Fetch admin.conf for local use"
  ansible.builtin.fetch:
    src: "/etc/kubernetes/admin.conf"
    dest: "{{ playbook_dir }}/"
    flat: true

- name: "Fetch super-admin.conf for local use"
  ansible.builtin.fetch:
    src: "/etc/kubernetes/super-admin.conf"
    dest: "{{ playbook_dir }}/"
    flat: true
