---
apiVersion: v2
name: node-feature-discovery-meta
version: 0.1.0
dependencies:
- name: node-feature-discovery
  version: 0.14.3
  repository: https://kubernetes-sigs.github.io/node-feature-discovery/charts
