---
apiVersion: v1
kind: Service
metadata:
  name: plexpy
  labels:
    k8s-app: plexpy
spec:
  ports:
  - port: 8181
    targetPort: 8181
    protocol: TCP
    name: http
  selector:
    k8s-app: plexpy
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: plexpy
  labels:
    k8s-app: plexpy
spec:
  replicas: 1
  template:
    metadata:
      labels:
        k8s-app: plexpy
    spec:
      containers:
      - name: plexpy
        image: linuxserver/plexpy
        ports:
        - containerPort: 8181
        volumeMounts:
          - mountPath: "/config"
            name: config
      volumes:
        - nfs:
            server: fs1.oneill.net
            path: /volume1/k8s-pv/static/plexpy-config
          name: config
