---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: 1password

resources:
- namespace.yaml
- helm/connect/templates/connect-deployment.yaml
- helm/connect/templates/service.yaml

secretGenerator:
- name: op-credentials
  files:
  - 1password-credentials.json
  type: Opaque
