---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- cert-manager.yaml
- clusterissuer.yaml

secretGenerator:
- name: cert-manager
  namespace: cert-manager
  env: secret.txt
  type: Opaque
  options:
    # Disabled because kustomize doesn't properly replace the reference in the cluster issuer CRD
    disableNameSuffixHash: true

