---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- helm/templates/crds.yaml
- helm/templates/deployment.yaml
- helm/templates/webhook-deployment.yaml
- helm/templates/webhook-serviceaccount.yaml
- helm/templates/cainjector-deployment.yaml
- helm/templates/webhook-service.yaml
- helm/templates/startupapicheck-serviceaccount.yaml
- helm/templates/startupapicheck-job.yaml
- helm/templates/service.yaml
- helm/templates/rbac.yaml
- helm/templates/webhook-mutating-webhook.yaml
- helm/templates/webhook-config.yaml
- helm/templates/webhook-rbac.yaml
- helm/templates/serviceaccount.yaml
- helm/templates/cainjector-rbac.yaml
- helm/templates/startupapicheck-rbac.yaml
- helm/templates/webhook-validating-webhook.yaml
- helm/templates/cainjector-serviceaccount.yaml
- letsencrypt.yaml
- self-signed.yaml

secretGenerator:
- name: cert-manager
  namespace: cert-manager
  env: secret.txt
  type: Opaque
  options:
    # Disabled because kustomize doesn't properly replace the reference in the cluster issuer CRD
    disableNameSuffixHash: true

