---
name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Install Nix
        uses: cachix/install-nix-action@f0fe604f8a612776892427721526b4c7cfb23aba # v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup development environment
        run: nix develop --command echo "Development environment ready"

      - name: Install Ansible Galaxy roles
        run: nix develop --command ./ansible/scripts/docker-nix-wrapper.sh ansible-galaxy install -r ansible/galaxy.yaml -p ansible/roles/galaxy

      - name: Write vault password file
        run: echo "$ANSIBLE_VAULT_PASSWORD" > ansible/ansible-vault-password
        env:
          ANSIBLE_VAULT_PASSWORD: ${{ secrets.ANSIBLE_VAULT_PASSWORD }}

      - name: Run lint
        run: nix develop --command ./scripts/lint
