name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install OpenTofu
      uses: opentofu/setup-opentofu@v1
      with:
        tofu_version: '1.6.0'

    - name: Install additional tools
      run: |
        # Install tflint
        curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash

        # Install trivy
        sudo apt-get update
        sudo apt-get install wget apt-transport-https gnupg lsb-release
        wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
        echo "deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main" | sudo tee -a /etc/apt/sources.list.d/trivy.list
        sudo apt-get update
        sudo apt-get install trivy

        # Install deadnix
        wget -O deadnix https://github.com/astro/deadnix/releases/latest/download/deadnix-x86_64-unknown-linux-musl
        chmod +x deadnix
        sudo mv deadnix /usr/local/bin/

    - name: Run pre-commit
      uses: pre-commit/action@v3.0.1
